FROM python:3.6-slim

RUN mkdir /app /root/opt
WORKDIR /app

COPY ./files/devrequirements.txt /app/devrequirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libc6-dev zsh \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r devrequirements.txt \
    && apt-get purge -y --auto-remove gcc libc6-dev

COPY ./files/profile /root/.profile
COPY ./files/zshrc /root/.zshrc
COPY ./files/oh-my-zsh/ /root/.oh-my-zsh/
COPY ./files/zsh-syntax-highlighting/ /root/opt/zsh-syntax-highlighting

VOLUME /app

CMD /bin/zsh
