#!/bin/sh

if [[ -z "${PGADMIN_DEFAULT_EMAIL}" && -f "${PGADMIN_DEFAULT_EMAIL_PATH}" ]] ; then
  echo "Using PGADMIN_DEFAULT_EMAIL_PATH to populate PGADMIN_DEFAULT_EMAIL"
  export PGADMIN_DEFAULT_EMAIL=$(cat "$PGADMIN_DEFAULT_EMAIL_PATH")
fi

if [[ -z "${PGADMIN_DEFAULT_PASSWORD}" && -f "${PGADMIN_DEFAULT_PASSWORD_PATH}" ]] ; then
  echo "Using PGADMIN_DEFAULT_PASSWORD_PATH to populate PGADMIN_DEFAULT_PASSWORD"
  export PGADMIN_DEFAULT_PASSWORD=$(cat "$PGADMIN_DEFAULT_PASSWORD_PATH")
fi

/entrypoint.sh $@
