version: 2.1

commands:
  build_image:
    description: Build a docker image and push it to DockerHub
    parameters:
      tag: { type: string }
      srcdir: { type: string }
    steps:
      - run:
          name: Build and push << parameters.tag >>
          command: |
            ./build-image-dir.sh \
                ~/cache/dirstate \
                "<< parameters.tag >>" \
                "<< parameters.srcdir >>"


jobs:
  build-all:
    docker:
      - image: cimg/base:2020.01
#      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          name: "Restoring dir state cache"
          key: dirstate
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - build_image:
          tag: novopl/python:3.6
          srcdir: python/3.6
      - build_image:
          tag: novopl/python:3.6-dev
          srcdir: python/3.6/dev
      - build_image:
          tag: novopl/python:3.7
          srcdir: python/3.7
      - build_image:
          tag: novopl/python:3.7-dev
          srcdir: python/3.7/dev
      - build_image:
          tag: novopl/python:3.8
          srcdir: python/3.8
      - build_image:
          tag: novopl/python:3.8-dev
          srcdir: python/3.8/dev
      - build_image:
          tag: novopl/python:3.8-fastapi
          srcdir: python/3.8/fastapi
      - save_cache:
          name: "Saving dir state cache"
          key: dirstate
          paths:
            - ~/cache/dirstate


workflows:
  version: 2
  main:
    jobs:
      - build-all
