#!/bin/zsh
# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"
export TERM=xterm-256color
# pyenv setting to build shared python library as well. Might be used
# by third party packages
export PYTHON_CONFIGURE_OPTS=--enable-shared

# ENV variables
source ~/.profile

ZSH_THEME="gentoo"

plugins=(git archlinux systemd sudo)


DISABLE_AUTO_UPDATE="true"
source $ZSH/oh-my-zsh.sh

NVM_INIT_PATH="/usr/share/nvm/init-nvm.sh"
if [ -e "$NVM_INIT_PATH" ]; then
    source $NVM_INIT_PATH
fi

bindkey -v
bindkey "^R" history-incremental-search-backward
bindkey "^E" sudo-command-line



###############################################################################
###############################################################################
###############################################################################

# The following lines were added by compinstall
zstyle :compinstall filename "${HOME}/.zshrc"
unsetopt share_history


fpath=(~/.zsh/completion $fpath)

# Completion
#autoload -Uz compinit
autoload -U compinit
compinit

# Prompt
# autoload -U promptinit
# promptinit
# prompt gentoo

# Options.
#setopt      correctall
setopt      autocd
unsetopt    beep


# History 
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Override the default variables.
export COLORTERM=yes

# GNU Colors
[ -f /etc/DIR_COLORS ] && eval $(dircolors -b /etc/DIR_COLORS)
export ZLSCOLORS="${LS_COLORS}"
export LESSOPEN="|lesspipe.sh %s"


# Keys
bindkey '^[OH'      beginning-of-line
bindkey '^[OF'      end-of-line
bindkey '^[[1;5D'   backward-word
bindkey '^[[1;5C'   forward-word
bindkey '^[[3~'     delete-char
bindkey '^R'        history-incremental-search-backward

# Aliases.
alias ls='ls --group-directories-first --color=auto'
alias ll='ls -lh'
alias lse='ls $(find . -maxdepth 1 -executable -type f | sed "s?^./??")'
alias lle='ll $(find . -maxdepth 1 -executable -type f | sed "s?^./??")'
alias lsd='ls -d $(find . -maxdepth 1 -executable -type d | sed "s?^./??")'
alias lld='ll -d $(find . -maxdepth 1 -executable -type d | sed "s?^./??")'
alias lsl='ls -d $(find . -maxdepth 1 -executable -type l | sed "s?^./??")'
alias lll='ll -d $(find . -maxdepth 1 -executable -type l | sed "s?^./??")'
alias lsf='ls -d $(find . -maxdepth 1 -type f ! -executable | sed "s?^./??")'
alias llf='ll -d $(find . -maxdepth 1 -type f ! -executable | sed "s?^./??")'
alias lsblk='lsblk -o name,type,fstype,size,label,uuid,mountpoint'
alias gitdiff='git diff --no-ext-diff'
alias packer='packer --noedit'
alias gitlogall='git log --oneline --reverse'
alias gitlog='git log --oneline --reverse --author $(git config --get user.email)'
alias playvid='mplayer -subcp enca:pl:cp1250'
alias cloc='cloc --by-file-by-lang'
alias gmv='git mv'
alias uiopen='xdg-open'
alias listdisk='lsblk --output NAME,UUID,SIZE,TYPE,FSTYPE,MOUNTPOINT'
alias update-arch='sudo pacman -Syu'
alias update-aur='sudo packer -Syu --noedit'
alias qpacker='packer --noedit'
alias activate='. ./env/bin/activate'



# Eclipse
export ECLIPSE_XMS=256M
export ECLIPSE_XMX=256M


# Try to enable zsh-syntax-highlighting
if [ -e "${HOME}/opt/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source  "${HOME}/opt/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
elif [ -e "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
else
    echo -e "\x1b[33mNo zsh-syntax-highlighting found\x1b[0m"
fi

